spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nguleduy/spring-boot-kafka-microservice.git/
          search-paths:
            - "configuration-properties/{application}/{profile}"
